@adress = http://localhost:3001/api/reports
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjI4ZWE5YzVmMmZjNjQyZjY4NDY2M2RhIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NTM1MTY3NDIsImV4cCI6MTY1MzU1Mjc0Mn0._fSLTkMh4jqwrh9H2UCRXhtf8e_XQnvS1Ofta_og978



### Get All 
GET {{adress}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Get All and approved
GET {{adress}}?includeStatus=approved,rejected
Content-Type: application/json
Authorization: Bearer {{token}}



### Create new report
POST {{adress}}
Content-Type:  application/json

{
    "set": "628eaa36f2fc642f684665b3",
    "task": "628eaa36f2fc642f684665b7",
    "description": "This is a test report"
}

